# Copyright 2022 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51
#

import random
import os

def generate_vmem_file(filename, num_words, word_length):
    with open(filename, 'w') as vmem_file:
        vmem_file.write("/* This code is autogenerated. */\n")
        for word_value in range(num_words):
            if word_value == 0:
                word_hex = '1032207098001032'
            elif word_value == 1:
                word_hex = '3210E20020709800'
            else:
                word_hex = ''.join(random.choice('0123456789ABCDEF') for _ in range(word_length))
            
            vmem_file.write(f'@{word_value:08X} {word_hex}\n')

if __name__ == "__main__":
    # Get the current working directory
    current_directory = os.getcwd()

    # Memory file with 8 words of 64 bits each
    filename_custom_values = os.path.join(current_directory, "idma_preload_values.vmem")
    num_words_custom_values = 8
    word_length_custom_values = 16  # 64 bits (16 hex digits)
    generate_vmem_file(filename_custom_values, num_words_custom_values, word_length_custom_values)
